import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SiderBar from "@/components/SiderBar";
import Footer from "@/components/Footer";
import ClientProviders from "@/components/ClientProviders";
import ScrollableArea from "@/components/ScrollableArea";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ margin: 0, padding: 0, height: "100dvh", overflow: "hidden" }}
      >
        <ClientProviders>
          <div
            style={{ display: "flex", height: "100dvh", overflow: "hidden" }}
          >
            <SiderBar />
            <ScrollableArea>
              <main style={{ flex: 1 }}>{children}</main>
              <Footer type="home" />
            </ScrollableArea>
          </div>
        </ClientProviders>
      </body>
    </html>
  );
}
